### ISSUE TITLE
Problem with Starting the Plugin

### ISSUE THREAD

**Issue by Techno3600** [WheezyGold7931/Mineplex-Core#20]
Here it is:
https://pastebin.com/E23Qi5D1
http://imgur.com/a/aw8bM

Why doesn't it work?

Thanks

**Comment by WheezyGold7931** [comment]
Skript does not look loaded...or exciting

**Comment by PixelMaster3D** [comment]
I'm just going to throw a theory out here. But, I think why its not loading because you have modified the script or you could have an incorrect version of one the required plugins. Just a theory of what might had happen. I was just skimming thru the log and just throwing out answers. That's all. If I were you, I would double check to make sure you have everything correct to launch the script.

**Comment by Torksi** [comment]
You must use Spigot 1.8, not Bukkit

**Comment by Techno3600** [comment]
I do use spigot, I was just showing you bukkit's startup also

**Comment by WheezyGold7931** [comment]
I don't think you put the skript in the scripts folder?

**Comment by WheezyGold7931** [comment]
As for support in discord https://discord.gg/y3Nss

**Comment by WheezyGold7931** [comment]
Closing issue #20 due to it not being an MCR bug itself

**Comment by WheezyGold7931** [comment]
Closing issue #20 due to it not being an MCR bug itself
